List<Map<String,dynamic>> dum  =
[
{
  "img":"assets/images/hoo1.jpg",
"imgg" :"assets/images/ho1.jpg",
"name" :"Crown plasa",
"rate" :"180/night",
"des" :"5 star hotel",
"ratings" : "4.5",

},
{
  "img":"assets/images/hoo2.jpg",
"imgg" :"assets/images/ho2.jpg",
"name" :"king",
"rate" :"190/night",
"des" :"5 star hotel",
"ratings" : "4.5",

},
{
  "img":"assets/images/hoo3.jpg",
"imgg" :"assets/images/ho3.jpg",
"name" :"queen",
"rate" :"200/night",
"des" :"5 star hotel",
"ratings" : "4.5",

},
{
  "img":"assets/images/hoo4.jpg",
"imgg" :"assets/images/ho4.jpg",
"name" :"star",
"rate" :"210/night",
"des" :"5 star hotel",
"ratings" : "4.5",
},
{
  "img":"assets/images/hoo5.jpg",
"imgg" :"assets/images/ho5.jpg",
"name" :"great",
"rate" :"220/night",
"des" :"5 star hotel",
"ratings" : "4.5",
},
{
  "img":"assets/images/hoo6.jpg",
"imgg" :"assets/images/ho6.jpg",
"name" :"rose",
"rate" :"230/night",
"des" :"5 star hotel",
"ratings" : "4.5",
},
{
  "img":"assets/images/hoo7.jpg",
"imgg" :"assets/images/ho7.jpg",
"name" :"lifa",
"rate" :"240/night",
"des" :"5 star hotel",
"ratings" : "4.5",
},
{
  "img":"assets/images/hoo8.jpg",
"imgg" :"assets/images/ho8.jpg",
"name" :"kik spot",
"rate" :"250/night",
"des" :"5 star hotel",
"ratings" : "4.5",
},
{
  "img":"assets/images/hoo9.jpg",
"imgg" :"assets/images/ho9.jpg",
"name" :"star kingdom",
"rate" :"260/night",
"des" :"5 star hotel",
"ratings" : "4.5",
},
{
  "img":"assets/images/hoo10.jpg",
"imgg" :"assets/images/ho10.jpg",
"name" :"nation",
"rate" :"270/night",
"des" :"5 star hotel",
"ratings" : "4.5",
},
];